[package]
name = "sync_server"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "entity", "migration"]
resolver = "2"

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }
axum = { version = "0.8.9", features = ["macros"] }
tokio = { version = "1.53.1", features = ["full"] }
tower = { version = "0.5.3", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tower-http = { version = "0.7.0", features = ["request-id", "trace"] }
dotenvy = "0.15.7"
sea-orm = { version = "2.0.2", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
    "with-json",
    "with-chrono",
    "with-uuid",
] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
rand = { version = "0.10.2", features = ["serde"] }
anyhow = { version = "1.0.104", features = ["backtrace"] }
argon2 = { version = "0.5.3", features = ["std"] }
chrono = { version = "0.4.45", features = ["serde"] }
uuid = { version = "1.24.1", features = ["serde", "v4", "fast-rng"] }
sha2 = "0.11.0"
lazy_static = "1.5.0"
async-trait = "0.1.92"
thiserror = "2.0.20"
aws-sdk-s3 = { version = "1.142.0", features = ["behavior-version-latest"] }
aws-config = { version = "1.10.1", features = ["behavior-version-latest"] }

[features]
response-compression = [
    "tower-http/compression-br",
    "tower-http/compression-gzip",
    "tower-http/compression-zstd",
]
default = []
