[package]
name = "api-types"
edition = "2024"
version = "0.1.0"

[features]
default = []
server = ["dep:axum"]
client = []

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
chrono = { version = "0.4.45", features = ["serde"] }
http = "1"
axum = { version = "0.8.9", optional = true }
uuid = { version = "1.24.1", features = ["serde"] }
